route:
  group_by: ['alertname']
  group_wait: 10s     
  receiver: 'telegram_receiver'

receivers:
- name: 'telegram_receiver'
  telegram_configs:
  - api_url: 'https://api.telegram.org'
    bot_token: 'token vừa nãy ở bước 1'
    chat_id: cái id của group ở bước 3
